Update envRun

diff --git a/.bin/envRun b/.bin/envRun
--- a/.bin/envRun
+++ b/.bin/envRun
@@ -12,7 +12,19 @@ while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symli
   [[ $SOURCE != /* ]] && SOURCE="$SCRIPTDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
 done
 SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+CURDIR=`pwd`
+while [ ! -e "$CURDIR/package.json" ]; do
+    if [ "$CURDIR" == "/" ]; then
+        echo "Cannot find package.json" >&2
+	exit 1
+    fi
+    CURDIR=`cd $CURDIR/..; pwd`
+done
+
+cd $CURDIR
 
 eval $($SCRIPTDIR/dependencyEnv)
+
+cd - > /dev/null
 
 $@
